### ISSUE TITLE
Connection refused when accepting invite

### ISSUE THREAD

**Issue by av8ta** [regular/ssb-cms#2]
This project looks really interesting! The pub invite isn't working for me though :(

I'm on windows running the latest sbot 10.4.10

```powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\av8ta> $env:ssb_appname="ssb-cms"
PS C:\Users\av8ta> sbot whoami
{
  "id": "@PJuVjW0wcvrCOKogIFc8NFiM+WTHdqE6qo7yGPQT6os=.ed25519"
}
PS C:\Users\av8ta> sbot invite.accept "pub.postpossessive.org:10000:@W0usBc5dFcUVSShld7ybYveGGhhZ1u6cLwFH6lYPCDo=.ed2551
9~hQRcUrk2NDX/q3PqIWeqi+q4jwnxgO+vLJ61Ycng6tM="

C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\node_modules\muxrpcli\index.js:68
      throw err
      ^
Error: could not connect to server
    at C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\plugins\invite.js:192:29
    at C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\node_modules\ssb-client\index.js:96:20
  Error: could not connect to sbot
    at C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\node_modules\ssb-client\index.js:96:23
    at C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\node_modules\multiserver\compose.js:65:24
    at Socket.<anonymous> (C:\Users\av8ta\AppData\Roaming\nvm\v8.8.0\node_modules\scuttlebot\node_modules\multiserver\pl
ugins\net.js:38:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  Error: connect ECONNREFUSED 138.201.131.83:10000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1183:14)
PS C:\Users\av8ta>
```

**Comment by regular** [comment]
@av8ta Oh, sorry, the sbot wasn't running. I just started it. Can you try again?
